#针对docker run --name linux-command --rm -d -p 9665:3000 wcjiang/linux-command:latest 生成deployment和svc

apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux-command
  namespace: develop
spec:
    replicas: 1
    selector:
        matchLabels:
            app: linux-command
    template:
        metadata:
            labels:
                app: linux-command
        spec:
            containers:
                - name: linux-command
                  image: wcjiang/linux-command:latest
                  ports:
                      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: linux-command
    namespace: develop
spec:
    selector:
        app: linux-command
    ports:
        - port: 80
          targetPort: 3000
          protocol: TCP
    type: NodePort