apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: redis-server-peer-authentication
  namespace: mtls-demo
spec:
  selector:
      matchLabels:
        app: redis-server-istio
  mtls:
    mode: STRICT