apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mtls-demo
  name: redis-server-normal
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-server-normal
  template:
    metadata:
      labels:
        name: redis-server-normal
    spec:
      containers:
        - name: redis-server-normal
          image: bitnami/redis:6.2.6
          ports:
            - containerPort: 6379
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server-normal
  namespace: mtls-demo
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: service-port
  selector:
    name: redis-server-normal