apiVersion: v1
data:
  APOLLO_META: http://config.jidudev.com:8080
  CI_ENVIRONMENT_SLUG: zero
  GRPC_SERVER_PORT: "9090"
  JAVA_OPTS: -Xms2g -Xmx2g -Xmn1g -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    -XX:MaxDirectMemorySize=256m -XX:-OmitStackTraceInFastThrow -XX:+UseG1GC -XX:G1ReservePercent=25
    -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0 -XX:SurvivorRatio=8
    -XX:+DisableExplicitGC -XX:GCLogFileSize=30m -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails
    -XX:+PrintGCDateStamps -XX:+PrintAdaptiveSizePolicy -XX:+UseGCLogFileRotation
    -XX:ParallelGCThreads=4 -XX:ConcGCThreads=1 -XX:G1ConcRefinementThreads=5 -XX:+PrintReferenceGC
    -XX:+PrintFlagsFinal -XX:NumberOfGCLogFiles=5 -XX:+HeapDumpOnOutOfMemoryError
    -XX:HeapDumpPath="/app/logs/dump.hprof"  -Xloggc:/app/logs/gc.log -XX:+UseGCLogFileRotation
    -XX:NumberOfGCLogFiles=5  -XX:GCLogFileSize=10M -javaagent:./jacocoagent/jacocoagent.jar=output=tcpserver,address=*  -javaagent:./iastagent/iastagent.jar
  JIDU_CLUSTER: zero
  SERVER_CELL: zero
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: dev
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"APOLLO_META":"http://config.jidudev.com:8080","CI_ENVIRONMENT_SLUG":"zero","ENVIRONMENT":"dev","GRPC_SERVER_PORT":"9090","JAVA_OPTS":"-Xms2g -Xmx2g -Xmn1g -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -XX:MaxDirectMemorySize=256m -XX:-OmitStackTraceInFastThrow -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0 -XX:SurvivorRatio=8 -XX:+DisableExplicitGC -XX:GCLogFileSize=30m -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintAdaptiveSizePolicy -XX:+UseGCLogFileRotation -XX:ParallelGCThreads=4 -XX:ConcGCThreads=1 -XX:G1ConcRefinementThreads=5 -XX:+PrintReferenceGC -XX:+PrintFlagsFinal -XX:NumberOfGCLogFiles=5 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=\"/app/logs/dump.hprof\"  -Xloggc:/app/logs/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5  -XX:GCLogFileSize=10M -javaagent:./jacocoagent/jacocoagent.jar=output=tcpserver,address=*","JIDU_CLUSTER":"zero","NAMESRV_ADDR":"namesrv.jidudev.com:9876","SERVER_CELL":"zero","SERVER_PORT":"8080","SPRING_PROFILES_ACTIVE":"dev","TRACEENV":"https://trace.jidudev.com"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2022-01-23T07:45:34Z","name":"cluster-config","namespace":"develop","resourceVersion":"611996637","selfLink":"/api/v1/namespaces/develop/configmaps/cluster-config","uid":"e36db4df-e411-458a-85f9-bf6d08781f3a"}}
  name: cluster-config
  namespace: tls-test
